### ISSUE TITLE
What is difference between purescript-checked-exceptions

### ISSUE THREAD

**Issue by xgrommx** [JordanMartinez/purescript-veither#1]
I have one question what is difference between https://pursuit.purescript.org/packages/purescript-checked-exceptions/3.1.0?

**Comment by JordanMartinez** [comment]
There's at least two differences.

First, `ExceptV` is a monad transformer (which uses `Either` under the hood) whereas `Veither` is not. `Veither` works like a nested `Either` but without paying for the extra cost of boxing `Right`s (e.g. `Either a (Either b (Either c (Either d e)))` would have a value of `Right (Right (Right (Left d)))`). `Veither (a :: a, b :: b, c :: c, d :: d) e` would have the value of `VariantRep {type: "d", value: d}`.

Because it works like `either`, you get all the usual `Either` functions but which work on `Veither`: `vfromRight`, `vfromLeft`, `vnote`, `vhush`, `veither`.

Second, `ExceptV errorRows Identity a` is isomorphic to `Veither errorRows a`, but `Veither` has one less layer of "boxing" when it stores errors due to not being wrapped in `Either`'s `Left`.
```purescript
ExceptV (Variant errors) Identity a = Identity (Either (Variant errors) a)
-- ignoring the Identity for a moment, we get this when we have errors
Either (Variant errors) a = Left (VariantRep {type: "foo", value: Error}
-- vs just this if we just Veither
Veither errorRows a = VariantRep {type: "foo", value: Error}
```

If I created `VexceptT`, which is the same idea as `ExceptV` but without the `Either`...
```purescript
newtype VexceptT errors m a = VexceptT (m (Veither errors a))
```
Then I once again don't deal with the boxing of `Either`.
```purescript
ExceptV (Variant errors) m a = m (Left (VariantRep {type: "foo", value: Error})
-- vs
VexceptT errors m a = m (VariantRep {type: "foo", value: Error})
```

**Comment by JordanMartinez** [comment]
Let me know if you have any other questions.
